language: ruby
rvm:
  - "1.9.3"
  - "2.0.0"
  - jruby-19mode
install: rake new
script: rake
services: mongodb
jdk:
  - oraclejdk7
  - openjdk7
matrix:
  exclude:
    - rvm: 1.9.2
      jdk: openjdk7
    - rvm: 1.9.3
      jdk: oraclejdk7
    - rvm: 2.0.0
      jdk: openjdk7
    - rvm: 2.0.0
      jdk: oraclejdk7
